.PHONY: gen-frontend

gen-frontend:
    @cd /mnt/d/tiktok_e-commence/gomall/app/frontend/ && cwgo server --type HTTP --idl ./idl/frontend/auth_page.proto --service ./app/frontend -module gomall/app/frontend -I ./idl/